inventory_app/urls.py
from django.urls import path
from . import views
from . import charts

app_name = 'inventory'
urlpatterns = [
    #index
    path('', views.HomeRedirectView.as_view()),
    path('home', views.DashboardView.as_view(), name='index'),
    #supplier
    path('supplier/', views.SupplierView.as_view(), name='supplier'),
    path('add_supplier/', views.AddSupplierView.as_view(), name='add_supplier'),
    path('<int:supplier_id>/item_supplier/', views.ProductSupplierView.as_view(), name='product_supplier'),
    path('<int:supplier_id>/item_supplier/add_product/', views.AddProductView.as_view(), name='add_product'),
    #product
    path('product/', views.ProductView.as_view(), name='multiple_products'),
    path('product/add_product', views.AddProductView.as_view(), name='add_product_with_supplier'),
    path('<int:product_id>/product/', views.ProductView.as_view(), name='single_products'),
    path('<int:product_id>/edit_prices', views.EditProductPricesView.as_view(), name='edit_prices'),
    path('product/add_unit', views.AddUnitView.as_view(), name='add_unit'),
    #location
    path('locations/', views.LocationView.as_view(), name='locations'),
    path('<int:location_id>/product_locations/', views.ProducLocationView.as_view(), name='product_locations'),
    #inventory management urls
    path('purchase_inventory/', views.PurchaseInventoryView.as_view(), name='purchase_inventory'),
    path('transfer_inventory/', views.TransferInventoryView.as_view(), name='transfer_inventory'),
    path('sale_of_inventory/', views.SaleInventoryView.as_view(), name='sale_of_inventory'),
    #reports
    path('daily_sale_report/', views.DailySaleView.as_view(), name='daily_sale_report'),
    path('monthly_purchase_report/', views.MonthlyPurchaseView.as_view(), name='monthly_purchase_report'),
    #charts
    path('top10TurnoverProductBarGraph/', charts.top10TurnoverProductBarGraph, name='top10TurnoverProductBarGraph'),
    path('Last30DaySaleLineGraph/', charts.Last30DaySaleLineGraph.as_view(), name='Last30DaySaleLineGraph'),
]

mgmt_sys/urls.py
from django.contrib import admin
from django.urls import path, include
from inventory_app.views import HomeRedirectView
from inventory_app import charts

urlpatterns = [
    path('inventory/', include('inventory_app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', HomeRedirectView.as_view()),
    # charts
    path('top10TurnoverProductBarGraph/', charts.top10TurnoverProductBarGraph, name='top10TurnoverProductBarGraph'),
    path('Last30DaySaleLineGraph/', charts.Last30DaySaleLineGraph.as_view(), name='Last30DaySaleLineGraph'),
]

inventory_app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.views.generic import ListView, UpdateView, View, RedirectView
from .models import Supplier, Product, Location, PurchaseInventory, TransferInventory, ProductLocation,\
Unit, SalesOrder
from .forms import SupplierForm, ProductForm, ProductSupplierForm, LocationForm, \
    PurchaseInventoryForm, TransferInventoryForm, InventoryFormsets, PurchaseAndSalePriceEditForm,\
    UnitForm, SalesOrderForm
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import CreateView, FormView
from datetime import date
from django.db.models import DecimalField, Sum, ExpressionWrapper, F
from datetime import timedelta

# Create your views here.
#FOR DEBUGGING PURPOSES
import pdb

class HomeRedirectView(RedirectView):
  url = reverse_lazy('inventory:index')

class DashboardView(LoginRequiredMixin, View):
    template_name = 'inventory_app/dashboard.html'

    def getTop10HighestMarginProducts(self):
        productMargins = [(product.product_name, float(product.getSalePrice) - product.getWeightedAveragePurchasePrice,
                           100*((float(product.getSalePrice) - product.getWeightedAveragePurchasePrice)/float(product.getSalePrice)))
                          for product in Product.objects.all()]
        return (sorted(productMargins, key=lambda tup: tup[1], reverse=True))[:10]

    def get(self, request, *args, **kwargs):
        #pdb.set_trace()
        productMargins = self.getTop10HighestMarginProducts()
        todaysSale = SalesOrder().getTodaysTotalSale
        todaysCOGS = SalesOrder().getTodaysCostOfGoodsSold
        todaysGrossProfit = float(todaysSale) - todaysCOGS
        context = { 'daily_sale' : todaysSale,
                    'daily_cost_of_goods_sold' : todaysCOGS,
                    'daily_gross_profit' : todaysGrossProfit,
                    'product_margins': productMargins}
        return render(request, self.template_name, context)

class SupplierView(LoginRequiredMixin, ListView):
    template_name = 'inventory_app/supplier/supplier.html'
    context_object_name = 'supplier_list'
    paginate_by = 6
    def get_queryset(self):
        return Supplier.objects.all()

class ProductSupplierView(LoginRequiredMixin, ListView):
    template_name = 'inventory_app/supplier/product_supplier.html'
    context_object_name = 'product_supplier_list'
    paginate_by = 6

    def get_queryset(self):
        supplier_id = self.kwargs['supplier_id']
        supplier_name = Supplier.objects.get(pk=self.kwargs['supplier_id']).supplier_name
        supplier_product = (supplier_id, supplier_name, Supplier.objects.get(pk=self.kwargs['supplier_id']).products.all())
        return supplier_product

class ProductView(LoginRequiredMixin, ListView):
    template_name = 'inventory_app/product/product.html'
    context_object_name = 'product_list'
    paginate_by = 10
    product_id = None

    def get_queryset(self):
        if ('product_id' in self.kwargs):
            self.product_id = self.kwargs['product_id']
            found_product = get_object_or_404(Product, pk = self.product_id)
            return [found_product]
        return Product.objects.all()

class AddSupplierView(LoginRequiredMixin, CreateView):
    model = Supplier
    template_name = 'inventory_app/supplier/add_supplier.html'
    form_class = SupplierForm
    success_url = reverse_lazy('inventory:supplier')

    def form_valid(self, form):
        return super().form_valid(form)

class AddUnitView(LoginRequiredMixin, CreateView):
    model = Unit
    template_name = 'inventory_app/product/add_unit.html'
    form_class = UnitForm
    success_url = reverse_lazy('inventory:multiple_products')

    def form_valid(self, form):
        return super().form_valid(form)

class AddProductView(LoginRequiredMixin, CreateView):
    template_name = 'inventory_app/product/add_product.html'
    form_class = ProductForm
    success_url = reverse_lazy('inventory:multiple_products')

    def get(self, request, *args, **kwargs):
        if 'supplier_id' in kwargs:
            context = {'form': ProductForm(), 'supplier_id': self.kwargs['supplier_id']}
        else:
            context = {'form':  ProductSupplierForm(), 'supplier_id': None}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        if 'supplier_id' in kwargs:
            form = ProductForm(request.POST)
            supplier_id = self.kwargs['supplier_id']
            if form.is_valid():
                if form.addProduct(supplier_id) is True:
                    return HttpResponseRedirect(reverse('inventory:product_supplier', args=([supplier_id])))
            return render(request, self.template_name, context= {'supplier_id' : supplier_id,'form': form})
        else:
            form = ProductSupplierForm(request.POST)
            if form.is_valid():
                if form.addProductWithSupplier() is True:
                    return HttpResponseRedirect(self.success_url)
            return render(request, self.template_name, context={'form': form})

class EditProductPricesView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = PurchaseAndSalePriceEditForm
    template_name = 'inventory_app/product/edit_product_prices.html'
    context_object_name = 'editable_product'
    success_url = reverse_lazy('inventory:multiple_products')

    def get_context_data(self, **kwargs):
        product_id = self.kwargs['product_id']
        product = get_object_or_404(Product, pk=product_id)
        product_sale_price = product.getSalePrice
        product_purchase_price = product.getPurchasePrice
        context = {'product': product, 'product_sale_price': product_sale_price,
                   'product_purchase_price': product_purchase_price}
        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        intitial_data = {'purchase_price_per_unit': context['product_purchase_price'],
                          'sale_price_per_unit' : context['product_sale_price']}
        form = PurchaseAndSalePriceEditForm(request.GET or None, initial=intitial_data)
        context['form'] = form
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = PurchaseAndSalePriceEditForm(request.POST or None)
        product_id = self.kwargs['product_id']
        product = get_object_or_404(Product, pk=product_id)
        if form.is_valid():
            form.updatePrices(product)
            return HttpResponseRedirect(self.success_url)
        return render(request, self.template_name, self.context)

class LocationView(LoginRequiredMixin, FormView):
    template_name = 'inventory_app/location/location.html'
    form_class = LocationForm
    success_url = reverse_lazy('inventory:locations')

    def get(self, request, *args, **kwargs):
        current_locations = Location.objects.all()
        context = {'form': LocationForm(), 'locations': current_locations}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = LocationForm(request.POST)
        if form.is_valid():
            if form.addLocation() is True:
                return HttpResponseRedirect(self.success_url)
        return render(request, self.template_name, self.context)

class ProducLocationView(LoginRequiredMixin, ListView):
    template_name = 'inventory_app/location/product_location.html'
    context_object_name = 'product_stock'
    paginate_by = 8
    def get_queryset(self):
        location_id = self.kwargs['location_id']
        location = Location.objects.get(pk=self.kwargs['location_id'])
        products_at_location = ProductLocation.objects.filter(location=location)
        product_stock = [(prod.product.product_name, prod.product.unit.unit_name,
                          prod.stock_at_location) for prod in products_at_location]
        return product_stock

class PurchaseInventoryView(LoginRequiredMixin, FormView):
    template_name = 'inventory_app/manage_inventory/purchase_inventory.html'
    model = PurchaseInventory
    form_class = PurchaseInventoryForm
    success_url = reverse_lazy('inventory:multiple_products')
    intitial_data = [{'purchase_quantity': 0}]

    def get(self, request, *args, **kwargs):
        formset = InventoryFormsets.getPurchaseInventoryFormSet()
        purchase_inventory_form = formset(request.GET or None, initial=self.intitial_data)
        context = {'formset': purchase_inventory_form}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        formset = InventoryFormsets.getPurchaseInventoryFormSet()
        purchase_inventory_form = formset(request.POST, initial=self.intitial_data)
        if purchase_inventory_form.is_valid():
            for purchase_form in purchase_inventory_form:
                purchase_form.addPurchase()
            return HttpResponseRedirect(self.success_url)
        #TODO Error scenario
        return HttpResponseRedirect(self.success_url)

class TransferInventoryView(LoginRequiredMixin, FormView):
    template_name = 'inventory_app/manage_inventory/transfer_inventory.html'
    model = TransferInventory
    form_class = TransferInventoryForm
    success_url = reverse_lazy('inventory:locations')
    intitial_data = [{'purchase_quantity': 0}]

    def get(self, request, *args, **kwargs):
        formset = InventoryFormsets.getTransferInventoryFormSet()
        purchase_inventory_form = formset(request.GET or None, initial=self.intitial_data)
        context = {'formset': purchase_inventory_form}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        formset = InventoryFormsets.getTransferInventoryFormSet()

inventory_app/templates/inventory_app/product/add_product.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="form-group col-md-8 mb-0">
    {% if supplier_id is None %}
    <form action="{% url 'inventory:add_product_with_supplier' %}" method="post" class="form">
        {% csrf_token %}
        {{ form.media }}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    {% else %}
    <form action="{% url 'inventory:add_product' supplier_id  %}" method="post" class="form">
        {% csrf_token %}
        {{ form.media }}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    {% endif %}
</div>
{% endblock %}

inventory_app/templates/inventory_app/product/add_unit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="form-group col-md-8 mb-0">
    <form action="{% url 'inventory:add_unit' %}" method="post" class="form">
        {% csrf_token %}
        {{ form.media }}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

inventory_app/templates/inventory_app/product/edit_product_prices.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
            <th>Product Name</th>
            <th>Supplier</th>
            <th>Itroduction Date</th>
            <th>Description</th>
            <th>Current Stock Quantity</th>
        </tr>
      </thead>
      <tbody>
        <tr>
            <td>
                {{ product.product_name }}
            </td>
            <td>
                <a href="{% url 'inventory:product_supplier' product.supplier.id %}">
                  {{ product.supplier.supplier_name }}
                </a>
            </td>
            <td>{{ product.product_introduction_date }}</td>
            <td>{{ product.product_description }}</td>
            <td>{{ product.current_product_stock }}</td>
        </tr>
      </tbody>
    </table>
</div>
<div class="form-group col-md-6 mb-0">
    <form action="{% url 'inventory:edit_prices' product.id %}" method="post" class="form">
        {% csrf_token %}
        {{ form.media }}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
</div>
{% endblock %}

inventory_app/templates/inventory_app/product/product.html
{% extends "base.html" %}
{% block content %}
{% load icons %}
<!-- Font Awesome CSS -->
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      rel="stylesheet"
      integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
      crossorigin="anonymous"
>
<h2>Products</h2>

<a class="nav-link active" href="{% url 'inventory:add_product_with_supplier' %}">
  <span data-feather="home"></span>
    <button type="button" class="btn btn-info">Add Product</button>
<span class="sr-only">(current)</span>
</a>

{% if product_list %}
<div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
            <th>Product Name</th>
            <th>Supplier</th>
            <th>Itroduction Date</th>
            <th>Description</th>
            <th>Stock Quantity</th>
            <th>Unit</th>
            <th>Purchase price</th>
            <th>Sale price</th>
        </tr>
      </thead>
      <tbody>
        {% for product in product_list %}
            <tr>
                <td>
                    <a href="{% url 'inventory:single_products' product.id %}">
                        {{ product.product_name }}
                    </a>
                </td>
                <td>
                <a href="{% url 'inventory:product_supplier' product.supplier.id %}">
                  {{ product.supplier.supplier_name }}
                </a>
                </td>
                <td>{{ product.product_introduction_date }}</td>
                <td>{{ product.product_description }}</td>
                <td>{{ product.current_product_stock }}</td>
                <td>{{ product.unit.unit_name }}</td>
                <td>{{ product.getPurchasePrice }}</td>
                <td>{{ product.getSalePrice }}</td>
                <td><a href="{% url 'inventory:edit_prices' product.id %}" title="edit prices">{% icon 'pencil' %}</a></td>
            </tr>
        {% endfor %}
      </tbody>
    </table>
    {% include "pagination_snippet.html" %}
</div>
{% else %}
    <p>No products are available.</p>
{% endif %}
{% endblock %}