inventory_app/urls.py
from django.urls import path
from . import views
from . import charts

app_name = 'inventory'
urlpatterns = [
    #index
    path('', views.HomeRedirectView.as_view()),
    path('home', views.DashboardView.as_view(), name='index'),
    #supplier
    path('supplier/', views.SupplierView.as_view(), name='supplier'),
    path('add_supplier/', views.AddSupplierView.as_view(), name='add_supplier'),
    path('<int:supplier_id>/item_supplier/', views.ProductSupplierView.as_view(), name='product_supplier'),
    path('<int:supplier_id>/item_supplier/add_product/', views.AddProductView.as_view(), name='add_product'),
    #product
    path('product/', views.ProductView.as_view(), name='multiple_products'),
    path('product/add_product', views.AddProductView.as_view(), name='add_product_with_supplier'),
    path('<int:product_id>/product/', views.ProductView.as_view(), name='single_products'),
    path('<int:product_id>/edit_prices', views.EditProductPricesView.as_view(), name='edit_prices'),
    path('product/add_unit', views.AddUnitView.as_view(), name='add_unit'),
    #location
    path('locations/', views.LocationView.as_view(), name='locations'),
    path('<int:location_id>/product_locations/', views.ProducLocationView.as_view(), name='product_locations'),
    #inventory management urls
    path('purchase_inventory/', views.PurchaseInventoryView.as_view(), name='purchase_inventory'),
    path('transfer_inventory/', views.TransferInventoryView.as_view(), name='transfer_inventory'),
    path('sale_of_inventory/', views.SaleInventoryView.as_view(), name='sale_of_inventory'),
    #reports
    path('daily_sale_report/', views.DailySaleView.as_view(), name='daily_sale_report'),
    path('monthly_purchase_report/', views.MonthlyPurchaseView.as_view(), name='monthly_purchase_report'),
    #charts
    path('top10TurnoverProductBarGraph/', charts.top10TurnoverProductBarGraph, name='top10TurnoverProductBarGraph'),
    path('Last30DaySaleLineGraph/', charts.Last30DaySaleLineGraph.as_view(), name='Last30DaySaleLineGraph'),
]

mgmt_sys/urls.py
from django.contrib import admin
from django.urls import path, include
from inventory_app.views import HomeRedirectView
from inventory_app import charts

urlpatterns = [
    path('inventory/', include('inventory_app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', HomeRedirectView.as_view()),
    # charts
    path('top10TurnoverProductBarGraph/', charts.top10TurnoverProductBarGraph, name='top10TurnoverProductBarGraph'),
    path('Last30DaySaleLineGraph/', charts.Last30DaySaleLineGraph.as_view(), name='Last30DaySaleLineGraph'),
]

templates/base.html
<!doctype html>
{% load static %}
{# Load the tag library #}
{% load bootstrap4 %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Mgmt Sys">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>Inventory Management System</title>
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark flex-md-nowrap p-0 shadow">
      {% if user.is_authenticated %}
      <p class="navbar-brand col-sm-3 col-md-2 mr-0">User: {{ user.username }}</p>
      {% endif %}
      <h5 class="navbar-brand">Company Name</h5>
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          {% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'logout' %}">Sign out</a>
          {% endif %}
        </li>
      </ul>
    </nav>
    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                <span>Administration</span>
                <a class="d-flex align-items-center text-muted" href="#" aria-label="Add a new report">
                  <span data-feather="plus-circle"></span>
                </a>
              </h6>
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'inventory:index' %}">
                  <span data-feather="home"></span>
                  Dashboard <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#"
                   role="button" aria-haspopup="true" aria-expanded="false">
                      Suppliers
                  </a>
                  <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'inventory:supplier' %}">List of Suppliers</a>
                    <a class="dropdown-item" href="{% url 'inventory:add_supplier' %}">Add Supplier</a>
                  </div>
              </li>
              <li class="nav-item">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#"
                   role="button" aria-haspopup="true" aria-expanded="false">
                    Products
                  </a>
                  <div class="dropdown-menu">
                      <a class="dropdown-item" href="{% url 'inventory:multiple_products' %}">List of Products</a>
                      <a class="dropdown-item" href="{% url 'inventory:add_product_with_supplier' %}">Add Product</a>
                      <a class="dropdown-item" href="{% url 'inventory:add_unit' %}">Add Unit</a>
                  </div>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'inventory:locations' %}">
                  <span data-feather="users"></span>
                  Locations
                </a>
              </li>
            </ul>
            <ul class="nav flex-column">
              <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                <span>Manage Inventory</span>
                <a class="d-flex align-items-center text-muted" href="#" aria-label="Add a new report">
                  <span data-feather="plus-circle"></span>
                </a>
              </h6>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'inventory:purchase_inventory' %}">
                  <span data-feather="layers"></span>
                  Inventory Purchase
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'inventory:transfer_inventory' %}">
                  <span data-feather="layers"></span>
                  Inventory Transfer
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'inventory:sale_of_inventory' %}">
                  <span data-feather="layers"></span>
                  Inventory Sale
                </a>
              </li>
            </ul>
            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
              <span>Reports</span>
              <a class="d-flex align-items-center text-muted" href="#" aria-label="Add a new report">
                <span data-feather="plus-circle"></span>
              </a>
            </h6>
            <ul class="nav flex-column mb-2">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'inventory:daily_sale_report' %}">
                  <span data-feather="file-text"></span>
                  Daily Sales Report
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'inventory:monthly_purchase_report' %}">
                  <span data-feather="file-text"></span>
                  Monthly Purchase Report
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Last quarter
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Year-end sale
                </a>
              </li>
            </ul>
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
            {% block content %}{% endblock %}
        </main>
      </div>
    </div>
  </body>
<footer class="footer">
  <div class="fixed-bottom">
    <span class="text-muted">Version 0.1</span>
  </div>
</footer>
</html>

templates/pagination_snippet.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;
          </a>
      </li>
    {% else %}
      <li class="page-item disabled">
          <a class="page-link" href="#" tabindex="-1"><span>&laquo;</span></a>
      </li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="page-item active">
            <a class="page-link" href="#">
                <span>{{ i }} <span class="sr-only">(current)</span></span>
            </a>
        </li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="page-item disabled">
          <a class="page-link" href="#" tabindex="-1"><span>&raquo;</span></a>
      </li>
    {% endif %}
  </ul>
{% endif %}